pool:
  vmImage: 'vs2017-win2016'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build'
- script: dotnet test test/InitLocals.TestRunner --configuration $(buildConfiguration) --no-build --no-restore
  displayName: 'dotnet test'
- task: CopyFiles@2
  inputs:
    contents: 'bin\**\*.nupkg'
    flattenFolders: true
    targetFolder: $(Build.ArtifactStagingDirectory)
- task: PublishBuildArtifacts@1
  inputs:
    artifactName: drop
- task: NuGetCommand@2
  displayName: 'NuGet push'
  inputs:
    command: push
    publishVstsFeed: 'InitLocals'
    allowPackageConflicts: true
